package com.soupthatisthick.encounterbuilder.logic.enums;

import com.soupthatisthick.encounterbuilder.logic.Challenge;

import java.util.HashSet;
import java.util.Set;

public enum MonsterEnum {
//	CRAWLING_CLAW(				"Undead",					Challenge.CR_0,			44),
//	LEMURE(						"Fiend (evil)",			Challenge.CR_0,				76),
//	SHRIEKER(					"Plant",					Challenge.CR_0,			138),
//	HOMUNCULUS(					"Construct",				Challenge.CR_0,			188),
//	MYCONID_SPROUT(				"Plant",					Challenge.CR_0,			230),
//	AWAKENED_SHRUB(				"Plant",					Challenge.CR_0,			317),
//	BABOON(						"Beast",					Challenge.CR_0,			318),
//	BADGER(						"Beast",					Challenge.CR_0,			318),
//	BAT(						"Beast",					Challenge.CR_0,			318),
//	CAT(						"Beast",					Challenge.CR_0,			320),
//	CRAB(						"Beast",					Challenge.CR_0,			320),
	DEER(						"Beast",					Challenge.CR_0,			321),
//	EAGLE(						"Beast",					Challenge.CR_0,			322),
//	FROG(						"Beast",					Challenge.CR_0,			322),
	GIANT_FIRE_BEETLE(			"Beast",					Challenge.CR_0,			325),		
//	GOAT(						"Beast",					Challenge.CR_0,			330),
//	HAWK(						"Beast",					Challenge.CR_0,			330),
//	HYENA(						"Beast",					Challenge.CR_0,			331),
//	JACKAL(						"Beast",					Challenge.CR_0,			331),
//	LIZARD(						"Beast",					Challenge.CR_0,			332),
//	OCTOPUS(					"Beast",					Challenge.CR_0,			333),
//	OWL(						"Beast",					Challenge.CR_0,			333),
//	QUIPPER(					"Beast",					Challenge.CR_0,			335),
//	RAT(						"Beast",					Challenge.CR_0,			335),
//	RAVEN(						"Beast",					Challenge.CR_0,			335),
//	SCORPION(					"Beast",					Challenge.CR_0,			337),
//	SEA_HORSE(					"Beast",					Challenge.CR_0,			337),
//	SPIDER(						"Beast",					Challenge.CR_0,			337),
//	VULTURE(					"Beast",					Challenge.CR_0,			339),
//	WEASEL(						"Beast",					Challenge.CR_0,			340),
	COMMONER(					"Humanoid",					Challenge.CR_0,			345),		
//	TWIG_BLIGHT(				"Plant",					Challenge.CR_EIGHTH,		32),
//	MANES(						"Fiend (Demon)",			Challenge.CR_EIGHTH,		60),
//	FLUMPH(						"Aberration",				Challenge.CR_EIGHTH,		135),
	KOBOLD(						"Humanoid",					Challenge.CR_EIGHTH,		195),		
//	MERFOLK(					"Humanoid",					Challenge.CR_EIGHTH,		218),
//	MONODRONE(					"Construct",				Challenge.CR_EIGHTH,		224),
//	SLAAD_TADPOLE(				"Aberration",				Challenge.CR_EIGHTH,		276),
	STIRGE(						"Beast",					Challenge.CR_EIGHTH,		284),		
	BLOOD_HAWK(					"Beast",					Challenge.CR_EIGHTH,		319),		
//	CAMEL(						"Beast",					Challenge.CR_EIGHTH,		320),
//	FLYING_SNAKE(				"Beast",					Challenge.CR_EIGHTH,		322),
//	GIANT_CRAB(					"Beast",					Challenge.CR_EIGHTH,		324),
//	GIANT_RAT(					"Beast",					Challenge.CR_EIGHTH,		327),
//	GIANT_WEASEL(				"Beast",					Challenge.CR_EIGHTH,		329),
//	MASTIFF(					"Beast",					Challenge.CR_EIGHTH,		332),
//	MULE(						"Beast",					Challenge.CR_EIGHTH,		333),
//	POISONOUS_SNAKE(			"Beast",					Challenge.CR_EIGHTH,		334),
//	PONY(						"Beast",					Challenge.CR_EIGHTH,		335),
	BANDIT(						"Humanoid",					Challenge.CR_EIGHTH,		343),		
	CULTIST(					"Humanoid",					Challenge.CR_EIGHTH,		345),		
	GUARD(						"Humanoid",					Challenge.CR_EIGHTH,		347),		
	NOBLE(						"Humanoid",					Challenge.CR_EIGHTH,		348),		
//	TRIBAL_WARRIOR(				"Humanoid",					Challenge.CR_EIGHTH,		350),
//	AARAKOCRA(					"Humanoid",					Challenge.CR_QUARTER,		12),
//	FLYING_SWORD(				"Construct",				Challenge.CR_QUARTER,		20),
//	NEEDLE_BLIGHT(				"Plant",					Challenge.CR_QUARTER,		32),
	BULLYWUG(					"Humanoid",					Challenge.CR_QUARTER,		35),		
//	DRETCH(						"Fiend (Demon)",			Challenge.CR_QUARTER,		57),
//	PTERANODON(					"Beast",					Challenge.CR_QUARTER,		80),
	DROW(						"Humanoid",					Challenge.CR_QUARTER,		128),		
//	VIOLET_FUNGUS(				"Plant",					Challenge.CR_QUARTER,		138),
	GOBLIN(						"Humanoid",					Challenge.CR_QUARTER,		166),		
//	GRIMLOCK(					"Humanoid",					Challenge.CR_QUARTER,		175),
//	KENKU(						"Humanoid",					Challenge.CR_QUARTER,		194),
	WINGED_KOBOLD(				"Humanoid",					Challenge.CR_QUARTER,		195),		
//	KUO_TOA(					"Humanoid",					Challenge.CR_QUARTER,		199),
//	MUD_MEPHIT(					"Elemental",				Challenge.CR_QUARTER,		216),
//	SMOKE_MEPHIT(				"Elemental",				Challenge.CR_QUARTER,		217),
//	STEAM_MEPHIT(				"Elemental",				Challenge.CR_QUARTER,		217),
//	DUODRONE(					"Construct",				Challenge.CR_QUARTER,		225),
	PIXIE(						"Fey",						Challenge.CR_QUARTER,		253),		
	PSEUDODRAGON(				"Dragon",					Challenge.CR_QUARTER,		254),		
	SKELETON(					"Undead",					Challenge.CR_QUARTER,		272),		
//	SPRITE(						"Fey",						Challenge.CR_QUARTER,		283),
	TROGLODYTE(					"Humanoid",					Challenge.CR_QUARTER,		290),		
//	ZOMBIE(						"Undead",					Challenge.CR_QUARTER,		316),
//	AXE_BEAK(					"Beast",					Challenge.CR_QUARTER,		317),
//	BLINK_DOG(					"Fey",						Challenge.CR_QUARTER,		318),
//	BOAR(						"Beast",					Challenge.CR_QUARTER,		319),
//	CONSTRICTOR_SNAKE(			"Beast",					Challenge.CR_QUARTER,		320),
//	DRAFT_HORSE(				"Beast",					Challenge.CR_QUARTER,		321),
	ELK(						"Beast",					Challenge.CR_QUARTER,		322),		
//	GIANT_BADGER(				"Beast",					Challenge.CR_QUARTER,		323),
//	GIANT_BAT(					"Beast",					Challenge.CR_QUARTER,		323),
	GIANT_CENTIPEDE(			"Beast",					Challenge.CR_QUARTER,		323),
	GIANT_FROG(					"Beast",					Challenge.CR_QUARTER,		325),
	GIANT_LIZARD(				"Beast",					Challenge.CR_QUARTER,		326),
	GIANT_OWL(					"Beast",					Challenge.CR_QUARTER,		327),
//	GIANT_POISONOUS_SNAKE(		"Beast",					Challenge.CR_QUARTER,		327),
//	GIANT_WOLF_SPIDER(			"Beast",					Challenge.CR_QUARTER,		330),
//	PANTHER(					"Beast",					Challenge.CR_QUARTER,		333),
//	RIDING_HORSE(				"Beast",					Challenge.CR_QUARTER,		336),
//	SWARM_OF_BATS(				"Beast",					Challenge.CR_QUARTER,		337),
	SWARM_OF_RATS(				"Beast",					Challenge.CR_QUARTER,		339),		
	SWARM_OF_RAVENS(			"Beast",					Challenge.CR_QUARTER,		339),		
	WOLF(						"Beast",					Challenge.CR_QUARTER,		341),		
	ACOLYTE(					"Humanoid",					Challenge.CR_QUARTER,		342),		
//	VINE_BLIGHT(				"Plant",					Challenge.CR_HALF,		32),
//	COCKATRICE(					"Monstrosity",				Challenge.CR_HALF,		42),
	DARKMANTLE(					"Monstrosity",				Challenge.CR_HALF,		46),		
//	GAS_SPORE(					"Plant",					Challenge.CR_HALF,		138),
	GNOLL(						"Humanoid",					Challenge.CR_HALF,		163),		
	GNOME_DEEP (				"HUMANOID(Svirfneblin)",	Challenge.CR_HALF,		164),		
	HOBGOBLIN(					"Humanoid",					Challenge.CR_HALF,		186),		
	JACKALWERE(					"Humanoid",					Challenge.CR_HALF,		193),		
	LIZARDFOLK(					"Humanoid",					Challenge.CR_HALF,		204),		
//	MAGMIN(						"Elemental",				Challenge.CR_HALF,		212),
//	DUST_MEPHIT(				"Elemental",				Challenge.CR_HALF,		215),
//	ICE_MEPHIT(					"Elemental",				Challenge.CR_HALF,		215),
//	MAGMA_MEPHIT(				"Elemental",				Challenge.CR_HALF,		216),
//	TRIDRONE(					"Construct",				Challenge.CR_HALF,		225),
//	MYCONID_ADULT(				"Plant",					Challenge.CR_HALF,		232),
	GRAY_OOZE(					"Ooze",						Challenge.CR_HALF,		243),		
	ORC(						"Humanoid",					Challenge.CR_HALF,		246),		
//	PIERCER(					"Monstrosity",				Challenge.CR_HALF,		252),
//	RUST_MONSTER(				"Monstrosity",				Challenge.CR_HALF,		262),
//	SAHUAGIN(					"Humanoid",					Challenge.CR_HALF,		263),
//	SATYR(						"Fey",						Challenge.CR_HALF,		267),
//	SHADOW(						"Undead",					Challenge.CR_HALF,		269),
//	WARHORSE_SKELETON(			"Undead",					Challenge.CR_HALF,		273),
//	APE(						"Beast",					Challenge.CR_HALF,		317),
	BLACK_BEAR(					"Beast",					Challenge.CR_HALF,		318),		
	CROCODILE(					"Beast",					Challenge.CR_HALF,		320),		
//	GIANT_GOAT(					"Beast",					Challenge.CR_HALF,		326),
//	GIANT_SEA_HORSE(			"Beast",					Challenge.CR_HALF,		328),
//	GIANT_WASP(					"Beast",					Challenge.CR_HALF,		329),
//	REEF_SHARK(					"Beast",					Challenge.CR_HALF,		336),
	SWARM_OF_INSECTS(			"Beast",					Challenge.CR_HALF,		338),		
	WARHORSE(					"Beast",					Challenge.CR_HALF,		340),		
//	WORG(						"Monstrosity",				Challenge.CR_HALF,		341),
	SCOUT(						"Humanoid",					Challenge.CR_HALF,		349),		
//	THUG(						"Humanoid",					Challenge.CR_HALF,		350),
//	ANIMATED_ARMOR(				"Construct",				Challenge.CR_1,			19),
//	BUGBEAR(					"Humanoid",					Challenge.CR_1,			33),
//	QUASIT(						"Fiend (Demon)",			Challenge.CR_1,			63),
//	IMP(						"Fiend (Devil)",			Challenge.CR_1,			76),
//	BRASS_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_1,			106),
//	COPPER_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_1,			112),
//	DRYAD(						"Fey",						Challenge.CR_1,			121),
//	DUERGAR(					"Humanoid",					Challenge.CR_1,			122),
//	FAERIE_DRAGON_YOUNG(		"Dragon",					Challenge.CR_1,			133),
	GHOUL(						"Undead",					Challenge.CR_1,			148),		
//	GOBLIN_BOSS(				"Humanoid",					Challenge.CR_1,			166),
//	HARPY(						"Monstrosity",				Challenge.CR_1,			181),
	HIPPOGRIFF(					"Monstrosity",				Challenge.CR_1,			184),		
	KUO_TOA_WHIP(				"Humanoid",					Challenge.CR_1,			200),		
//	QUADRONE(					"Construct",				Challenge.CR_1,			226),
//	QUAGGOTH_SPORE_SERVANT(		"Plant",					Challenge.CR_1,			230),
//	HALF_OGRE(					"Giant",					Challenge.CR_1,			238),
//	FIRE_SNAKE(					"Elemental",				Challenge.CR_1,			265),
//	SCARECROW(					"Construct",				Challenge.CR_1,			268),
	SPECTER(					"Undead",					Challenge.CR_1,			279),		
//	THRI_KREEN(					"Humanoid",					Challenge.CR_1,			288),
	YUAN_TI_PUREBLOOD(			"Monstrosity",				Challenge.CR_1,			310),		
//	BROWN_BEAR(					"Beast",					Challenge.CR_1,			319),
//	DEATH_DOG(					"Monstrosity",				Challenge.CR_1,			321),
//	DIRE_WOLF(					"Beast",					Challenge.CR_1,			321),
//	GIANT_EAGLE(				"Beast",					Challenge.CR_1,			324),
//	GIANT_HYENA(				"Beast",					Challenge.CR_1,			326),
//	GIANT_OCTOPUS(				"Beast",					Challenge.CR_1,			326),
	GIANT_SPIDER(				"Beast",					Challenge.CR_1,			328),		
//	GIANT_TOAD(					"Beast",					Challenge.CR_1,			329),
//	GIANT_VULTURE(				"Beast",					Challenge.CR_1,			329),
//	LION(						"Beast",					Challenge.CR_1,			331),
//	SWARM_OF_QUIPPERS(			"Beast",					Challenge.CR_1,			338),
//	TIGER(						"Beast",					Challenge.CR_1,			339),
	SPY(						"Humanoid",					Challenge.CR_1,			349),		
	RUG_OF_SMOTHERING(			"Construct",				Challenge.CR_2,			20),		
//	ANKHEG(						"Monstrosity",				Challenge.CR_2,			21),
//	AZER(						"Elemental",				Challenge.CR_2,			22),
	CARRION_CRAWLER(			"Monstrosity",				Challenge.CR_2,			37),		
//	CENTAUR(					"Monstrosity",				Challenge.CR_2,			38),
//	SPINED_DEVIL(				"Fiend (Devil)",			Challenge.CR_2,			78),
//	ALLOSAURUS(					"Beast",					Challenge.CR_2,			79),
//	PLESIOSAURUS(				"Beast",					Challenge.CR_2,			80),
//	BLACK_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_2,			88),
//	GREEN_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_2,			95),
//	WHITE_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_2,			102),
//	BRONZE_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_2,			109),
//	SILVER_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_2,			118),
	ETTERCAP(					"Monstrosity",				Challenge.CR_2,			131),		
//	FAERIE_DRAGON(				"Dragon",					Challenge.CR_2,			133),
//	GARGOYLE(					"Elemental",				Challenge.CR_2,			140),
//	GHAST(						"Undead",					Challenge.CR_2,			148),
//	GIBBERING_MOUTHER(			"Aberration",				Challenge.CR_2,			157),
//	GITHZERAI_MONK(				"Humanoid",					Challenge.CR_2,			161),
	GNOLL_PACK_LORD(			"Humanoid",					Challenge.CR_2,			163),		
//	GRICK(						"Monstrosity",				Challenge.CR_2,			173),
	GRIFFON(					"Monstrosity",				Challenge.CR_2,			174),		
//	SEA_HAG(					"Fey",						Challenge.CR_2,			179),
//	INTELLECT_DEVOURER(			"Aberration",				Challenge.CR_2,			191),
//	LIZARDFOLK_SHAMAN(			"Humanoid",					Challenge.CR_2,			205),
	WERERAT(					"Humanoid",					Challenge.CR_2,			209),		
	MERROW(						"Monstrosity",				Challenge.CR_2,			219),		
//	MIMIC(						"Monstrosity",				Challenge.CR_2,			220),
//	PENTADRONE(					"Construct",				Challenge.CR_2,			226),
//	MYCONID_SOVEREIGN(			"Plant",					Challenge.CR_2,			232),
//	NOTHIC(						"Aberration",				Challenge.CR_2,			236),
//	OGRE(						"Giant",					Challenge.CR_2,			237),
//	GELATINOUS_CUBE(			"Ooze",						Challenge.CR_2,			242),
//	OCHRE_JELLY(				"Ooze",						Challenge.CR_2,			243),
//	ORC_EYE_OF_GRUUMSH(			"Humanoid",					Challenge.CR_2,			247),
//	OROG(						"Humanoid",					Challenge.CR_2,			247),
//	PEGASUS(					"Celestial",				Challenge.CR_2,			250),
	PERYTON(					"Monstrosity",				Challenge.CR_2,			251),		
	QUAGGOTH(					"Humanoid",					Challenge.CR_2,			256),		
//	SAHUAGIN_PRIESTESS(			"Humanoid",					Challenge.CR_2,			264),
	MINOTAUR_SKELETON(			"Undead",					Challenge.CR_2,			273),		
	WILL_O_WISP(				"Undead",					Challenge.CR_2,			301),		
//	OGRE_ZOMBIE(				"Undead",					Challenge.CR_2,			316),
	AWAKENED_TREE(				"Plant",					Challenge.CR_2,			317),		
//	GIANT_BOAR(					"Beast",					Challenge.CR_2,			323),
//	GIANT_CONSTRICTOR_SNAKE(	"Beast",					Challenge.CR_2,			324),
//	GIANT_ELK(					"Beast",					Challenge.CR_2,			325),
//	HUNTER_SHARK(				"Beast",					Challenge.CR_2,			330),
//	POLAR_BEAR(					"Beast",					Challenge.CR_2,			334),
//	RHINOCEROS(					"Beast",					Challenge.CR_2,			336),
//	SABER_TOOTHED_TIGER(		"Beast",					Challenge.CR_2,			336),
//	SWARM_OF_POISONOUS_SNAKES(	"Beast",					Challenge.CR_2,			338),
//	BANDIT_CAPTAIN(				"Humanoid",					Challenge.CR_2,			344),
//	BERSERKER(					"Humanoid",					Challenge.CR_2,			344),
	CULT_FANATIC(				"Humanoid",					Challenge.CR_2,			345),		
//	DRUID(						"Humanoid",					Challenge.CR_2,			346),
//	PRIEST(						"Humanoid",					Challenge.CR_2,			348),
//	BASILISK(					"Monstrosity",				Challenge.CR_3,			24),
//	SPECTATOR(					"Aberration",				Challenge.CR_3,			30),
//	BUGBEAR_CHIEF(				"Humanoid",					Challenge.CR_3,			33),
//	BEARDED_DEVIL(				"Fiend (Devil)",			Challenge.CR_3,			70),
//	ANKYLOSAURUS(				"Beast",					Challenge.CR_3,			79),
	DISPLACER_BEAST(			"Monstrosity",				Challenge.CR_3,			81),		
	DOPPELGANGER(				"Monstrosity",				Challenge.CR_3,			82),		
//	BLUE_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_3,			91),
//	GOLD_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_3,			115),
//	GITHYANKI_WARRIOR(			"Humanoid",					Challenge.CR_3,			160),
	GRELL(						"Aberration",				Challenge.CR_3,			172),		
	GREEN_HAG(					"Fey",						Challenge.CR_3,			177),		
//	HELL_HOUND(					"Fiend",					Challenge.CR_3,			182),
	HOBGOBLIN_CAPTAIN(			"Humanoid",					Challenge.CR_3,			186),		
	HOOK_HORROR(				"Monstrosity",				Challenge.CR_3,			189),		
//	WEREWOLF(					"Humanoid",					Challenge.CR_3,			211),
//	MANTICORE(					"Monstrosity",				Challenge.CR_3,			213),
//	MINOTAUR(					"Monstrosity",				Challenge.CR_3,			223),
//	MUMMY(						"Undead",					Challenge.CR_3,			228),
//	NIGHTMARE(					"Fiend",					Challenge.CR_3,			235),
	OWLBEAR(					"Monstrosity",				Challenge.CR_3,			249),		
	WATER_WEIRD(				"Elemental",				Challenge.CR_3,			299),		
	WIGHT(						"Undead",					Challenge.CR_3,			300),		
//	YETI(						"Monstrosity",				Challenge.CR_3,			305),
	YUAN_TI_MALISON(			"Monstrosity",				Challenge.CR_3,			309),		
//	GIANT_SCORPION(				"Beast",					Challenge.CR_3,			327),
//	KILLER_WHALE(				"Beast",					Challenge.CR_3,			331),
//	PHASE_SPIDER(				"Monstrosity",				Challenge.CR_3,			334),
//	WINTER_WOLF(				"Monstrosity",				Challenge.CR_3,			340),
	KNIGHT(						"Humanoid",					Challenge.CR_3,			347),		
	VETERAN(					"Humanoid",					Challenge.CR_3,			350),		
//	BANSHEE(					"Undead",					Challenge.CR_4,			23),
	CHUUL(						"Aberration",				Challenge.CR_4,			40),		
//	COUATL(						"Celestial",				Challenge.CR_4,			43),
//	SHADOW_DEMON(				"Fiend (Demon)",			Challenge.CR_4,			64),
//	RED_DRAGON_WYRMLING(		"Dragon",					Challenge.CR_4,			98),
	ETTIN(						"Giant",					Challenge.CR_4,			132),		
//	FLAMESKULL(					"Undead",					Challenge.CR_4,			134),
	GHOST(						"Undead",					Challenge.CR_4,			147),		
//	GNOLL_FANG_OF_YEENOGHU(		"Humanoid",					Challenge.CR_4,			163),
	HELMED_HORROR(				"Construct",				Challenge.CR_4,			183),		
//	LAMIA(						"Monstrosity",				Challenge.CR_4,			201),
//	LIZARD_KING_QUEEN(			"Humanoid",					Challenge.CR_4,			205),
//	WEREBOAR(					"Humanoid",					Challenge.CR_4,			209),
//	WERETIGER(					"Humanoid",					Challenge.CR_4,			210),
//	BONE_NAGA(					"Undead",					Challenge.CR_4,			233),
//	BLACK_PUDDING(				"Ooze",						Challenge.CR_4,			241),
//	ORC_WAR_CHIEF(				"Humanoid",					Challenge.CR_4,			246),
//	SUCCUBUS_INCUBUS(			"Fiend",					Challenge.CR_4,			285),
//	ELEPHANT(					"Beast",					Challenge.CR_4,			322),
//	BULETTE(					"Monstrosity",				Challenge.CR_5,			34),
//	CAMBION(					"Fiend",					Challenge.CR_5,			36),
//	BARLGURA(					"Fiend (Demon)",			Challenge.CR_5,			56),
	BARBED_DEVIL(				"Fiend (Devil)",			Challenge.CR_5,			70),		
//	TRICERATOPS(				"Beast",					Challenge.CR_5,			80),
	AIR_ELEMENTAL(				"Elemental",				Challenge.CR_5,			124),		
	EARTH_ELEMENTAL(			"Elemental",				Challenge.CR_5,			124),		
	FIRE_ELEMENTAL(				"Elemental",				Challenge.CR_5,			125),		
	WATER_ELEMENTAL(			"Elemental",				Challenge.CR_5,			125),		
	DROW_ELITE_WARRIOR(			"Humanoid",					Challenge.CR_5,			128),		
//	HILL_GIANT(					"Giant",					Challenge.CR_5,			155),
//	FLESH_GOLEM(				"Construct",				Challenge.CR_5,			169),
	GORGON(						"Construct",				Challenge.CR_5,			171),		
//	NIGHT_HAG(					"Fiend",					Challenge.CR_5,			178),
	HALF_RED_DRAGON_VETERAN(	"Humanoid",					Challenge.CR_5,			180),		
//	WEREBEAR(					"Humanoid",					Challenge.CR_5,			208),
	OTYUGH(						"Aberration",				Challenge.CR_5,			248),		
//	YOUNG_REMORHAZ(				"Monstrosity",				Challenge.CR_5,			258),
	REVENANT(					"Undead",					Challenge.CR_5,			259),		
	ROPER(						"Monstrosity",				Challenge.CR_5,			261),		
//	SAHUAGIN_BARON(				"Humanoid",					Challenge.CR_5,			264),
//	SALAMANDER(					"Elemental",				Challenge.CR_5,			266),
	SHAMBLING_MOUND(			"Plant",					Challenge.CR_5,			270),		
//	RED_SLAAD(					"Aberration",				Challenge.CR_5,			276),
	TROLL(						"Giant",					Challenge.CR_5,			291),		
//	UMBER_HULK(					"Monstrosity",				Challenge.CR_5,			292),
//	UNICORN(					"Celestial",				Challenge.CR_5,			294),
	VAMPIRE_SPAWN(				"Undead",					Challenge.CR_5,			298),		
//	WRAITH(						"Undead",					Challenge.CR_5,			302),
//	XORN(						"Elemental",				Challenge.CR_5,			304),
//	MEZZOLOTH(					"Fiend",					Challenge.CR_5,			313),
//	BEHOLDER_ZOMBIE(			"Undead",					Challenge.CR_5,			316),
//	GIANT_CROCODILE(			"Beast",					Challenge.CR_5,			324),
//	GIANT_SHARK(				"Beast",					Challenge.CR_5,			328),
//	GLADIATOR(					"Humanoid",					Challenge.CR_5,			346),
//	CHIMERA(					"Monstrosity",				Challenge.CR_6,			39),
	CYCLOPS(					"Giant",					Challenge.CR_6,			45),		
	CHASME(						"Fiend (Demon)",			Challenge.CR_6,			57),		
	VROCK(						"Fiend (Demon)",			Challenge.CR_6,			64),		
//	WHITE_DRAGON_YOUNG(			"Dragon",					Challenge.CR_6,			101),
//	BRASS_DRAGON_YOUNG(			"Dragon",					Challenge.CR_6,			105),
//	DRIDER(						"Monstrosity",				Challenge.CR_6,			120),
//	GALEB_DUHR(					"Elemental",				Challenge.CR_6,			139),
//	GITHZERAI_ZERTH(			"Humanoid",					Challenge.CR_6,			161),
//	HOBGOBLIN_WARLORD(			"Humanoid",					Challenge.CR_6,			187),
//	INVISIBLE_STALKER(			"Elemental",				Challenge.CR_6,			192),
//	KUO_TOA_ARCHPRIEST(			"Humanoid",					Challenge.CR_6,			200),
//	MEDUSA(						"Monstrosity",				Challenge.CR_6,			214),
	WYVERN(						"Dragon",					Challenge.CR_6,			303),		
//	MAMMOTH(					"Beast",					Challenge.CR_6,			332),
	MAGE(						"Humanoid",					Challenge.CR_6,			347),		
//	BLACK_DRAGON_YOUNG(			"Dragon",					Challenge.CR_7,			88),
//	COPPER_DRAGON_YOUNG(		"Dragon",					Challenge.CR_7,			111),
//	DROW_MAGE(					"Humanoid",					Challenge.CR_7,			129),
	STONE_GIANT(				"Giant",					Challenge.CR_7,			156),		
//	GRICK_ALPHA(				"Monstrosity",				Challenge.CR_7,			173),
//	MIND_FLAYER(				"Aberration",				Challenge.CR_7,			222),
//	ONI(						"Giant",					Challenge.CR_7,			239),
//	SHIELD_GUARDIAN(			"Construct",				Challenge.CR_7,			271),
//	BLUE_SLAAD(					"Aberration",				Challenge.CR_7,			276),
//	YUAN_TI_ABOMINATION(		"Monstrosity",				Challenge.CR_7,			308),
//	GIANT_APE(					"Beast",					Challenge.CR_7,			323),
//	CLOAKER(					"Aberration",				Challenge.CR_8,			41),
//	HEZROU(						"Fiend (Demon)",			Challenge.CR_8,			60),
//	CHAIN_DEVIL(				"Fiend (Devil)",			Challenge.CR_8,			72),
//	TYRANNOSAURUS_REX(			"Beast",					Challenge.CR_8,			80),
//	GREEN_DRAGON_YOUNG(			"Dragon",					Challenge.CR_8,			94),
//	BRONZE_DRAGON_YOUNG(		"Dragon",					Challenge.CR_8,			108),
//	DROW_PRIESTESS_OF_LOLTH(	"Humanoid",					Challenge.CR_8,			129),
//	FOMORIAN(					"Giant",					Challenge.CR_8,			136),
//	FROST_GIANT(				"Giant",					Challenge.CR_8,			155),
//	GITHYANKI_KNIGHT(			"Humanoid",					Challenge.CR_8,			160),
//	HYDRA(						"Monstrosity",				Challenge.CR_8,			190),
//	SPIRIT_NAGA(				"Monstrosity",				Challenge.CR_8,			234),
//	GREEN_SLAAD(				"Aberration",				Challenge.CR_8,			277),
//	ASSASSIN(					"Humanoid",					Challenge.CR_8,			343),
//	GLABREZU(					"Fiend (Demon)",			Challenge.CR_9,			58),
	BONE_DEVIL(					"Fiend (Devil)",			Challenge.CR_9,			71),		
//	BLUE_DRAGON_YOUNG(			"Dragon",					Challenge.CR_9,			91),
//	SILVER_DRAGON_YOUNG(		"Dragon",					Challenge.CR_9,			118),
//	CLOUD_GIANT(				"Giant",					Challenge.CR_9,			154),
//	FIRE_GIANT(					"Giant",					Challenge.CR_9,			154),
//	CLAY_GOLEM(					"Construct",				Challenge.CR_9,			168),
//	GRAY_SLAAD(					"Aberration",				Challenge.CR_9,			277),
//	TREANT(						"Plant",					Challenge.CR_9,			289),
//	ABOMINABLE_YETI(			"Monstrosity",				Challenge.CR_9,			306),
//	NYCALOTH(					"Fiend",					Challenge.CR_9,			314),
//	ABOLETH(					"Aberration",				Challenge.CR_10,			13),
//	DEVA(						"Celestial",				Challenge.CR_10,			16),
//	YOCHLOL(					"Fiend (Demon)",			Challenge.CR_10,			65),
//	RED_DRAGON_YOUNG(			"Dragon",					Challenge.CR_10,			98),
//	GOLD_DRAGON_YOUNG(			"Dragon",					Challenge.CR_10,			115),
//	STONE_GOLEM(				"Construct",				Challenge.CR_10,			170),
//	GUARDIAN_NAGA(				"Monstrosity",				Challenge.CR_10,			234),
//	DEATH_SLAAD(				"Aberration",				Challenge.CR_10,			278),
//	BEHIR(						"Monstrosity",				Challenge.CR_11,			25),
//	HORNED_DEVIL(				"Fiend (Devil)",			Challenge.CR_11,			74),
	DAO(						"Elemental",				Challenge.CR_11,			143),		
//	DJINNI(						"Elemental",				Challenge.CR_11,			144),
	EFREETI(					"Elemental",				Challenge.CR_11,			145),		
//	MARID(						"Elemental",				Challenge.CR_11,			146),
//	REMORHAZ(					"Monstrosity",				Challenge.CR_11,			258),
//	ROC(						"Monstrosity",				Challenge.CR_11,			260),
//	GYNOSPHINX(					"Monstrosity",				Challenge.CR_11,			282),
//	ERINYES(					"Fiend (Devil)",			Challenge.CR_12,			73),
//	ARCANALOTH(					"Fiend",					Challenge.CR_12,			313),
//	ARCHMAGE(					"Humanoid",					Challenge.CR_12,			342),
//	BEHOLDER(					"Aberration",				Challenge.CR_13,			28),
//	NALFESHNEE(					"Fiend (Demon)",			Challenge.CR_13,			62),
//	SHADOW_DRAGON(				"Dragon",					Challenge.CR_13,			85),
	WHITE_DRAGON_ADULT(			"Dragon",					Challenge.CR_13,			101),		
//	BRASS_DRAGON_ADULT(			"Dragon",					Challenge.CR_13,			105),
	STORM_GIANT(				"Giant",					Challenge.CR_13,			156),		
//	RAKSHASA(					"Fiend",					Challenge.CR_13,			257),
	VAMPIRE(					"Undead",					Challenge.CR_13,			297),		
//	ULTROLOTH(					"Fiend",					Challenge.CR_13,			314),
//	DEATH_TYRANT(				"Undead",					Challenge.CR_14,			29),
//	ICE_DEVIL(					"Fiend (Devil)",			Challenge.CR_14,			75),
//	BLACK_DRAGON_ADULT(			"Dragon",					Challenge.CR_14,			88),
//	COPPER_DRAGON_ADULT(		"Dragon",					Challenge.CR_14,			111),
//	GREEN_DRAGON_ADULT(			"Dragon",					Challenge.CR_15,			94),
//	BRONZE_DRAGON_ADULT(		"Dragon",					Challenge.CR_15,			108),
	MUMMY_LORD(					"Undead",					Challenge.CR_15,			229),		
//	PURPLE_WORM(				"Monstrosity",				Challenge.CR_15,			255),
//	PLANETAR(					"Celestial",				Challenge.CR_16,			17),
//	MARILITH(					"Fiend (Demon)",			Challenge.CR_16,			61),
	BLUE_DRAGON_ADULT(			"Dragon",					Challenge.CR_16,			91),		
//	SILVER_DRAGON_ADULT(		"Dragon",					Challenge.CR_16,			117),
//	IRON_GOLEM(					"Construct",				Challenge.CR_16,			170),
//	DEATH_KNIGHT(				"Undead",					Challenge.CR_17,			47),
//	GORISTRO(					"Fiend (Demon)",			Challenge.CR_17,			59),
//	DRACOLICH(					"Undead",					Challenge.CR_17,			84),
//	RED_DRAGON_ADULT(			"Dragon",					Challenge.CR_17,			98),
//	GOLD_DRAGON_ADULT(			"Dragon",					Challenge.CR_17,			114),
//	DRAGON_TURTLE(				"Dragon",					Challenge.CR_17,			119),
//	ANDROSPHINX(				"Monstrosity",				Challenge.CR_17,			281),
//	DEMILICH(					"Undead",					Challenge.CR_18,			48),
//	BALOR(						"Fiend (Demon)",			Challenge.CR_19,			55),
//	PIT_FIEND(					"Fiend (Devil)",			Challenge.CR_20,			77),
//	WHITE_DRAGON_ANCIENT(		"Dragon",					Challenge.CR_20,			100),
//	BRASS_DRAGON_ANCIENT(		"Dragon",					Challenge.CR_20,			104),
//	SOLAR(						"Celestial",				Challenge.CR_21,			18),
//	BLACK_DRAGON_ANCIENT(		"Dragon",					Challenge.CR_21,			87),
//	COPPER_DRAGON_ANCIENT(		"Dragon",					Challenge.CR_21,			110),
//	LICH(						"Undead",					Challenge.CR_21,			202),
//	GREEN_DRAGON_ANCIENT(		"Dragon",					Challenge.CR_22,			93),
//	BRONZE_DRAGON_ANCIENT(		"Dragon",					Challenge.CR_22,			107),
//	BLUE_DRAGON_ANCIENT(		"Dragon",					Challenge.CR_23,			90),
//	SILVER_DRAGON_ANCIENT(		"Dragon",					Challenge.CR_23,			116),
//	EMPYREAN(					"Celestial",				Challenge.CR_23,			130),
//	KRAKEN(						"Monstrosity",				Challenge.CR_23,			197),
//	RED_DRAGON_ANCIENT(			"Dragon",					Challenge.CR_24,			97),
//	GOLD_DRAGON_ANCIENT(		"DRAGON",					Challenge.CR_24,			113),
//	TARRASQUE(					"Monstrosity",				Challenge.CR_30,			286)
;
	
	public final String				type;
	public final Challenge			cr;
	public final int				page;
	public final String				name;
	
	private MonsterEnum(String type, Challenge cr, int page) {
		this.type = type;
		this.cr = cr;
		this.page = page;
		name = toString();
	}
	
	
	public static final Set<MonsterEnum>	containingText(String text) {
		HashSet<MonsterEnum>	S = new HashSet<MonsterEnum>();
		for(MonsterEnum M : MonsterEnum.values()) {
			if (M.toString().contains(text)) {
				S.add(M);
			} else if (M.name().contains(text)) {
				S.add(M);
			}
		}
		return S;
	}
}
